version: '3'
services:
  # This is the node service
  p3appb:
    build: .
    container_name: "nodejs"
    image: p3appb.latest
    ports:
    - "80:3000"
    links:
    - db
    volumes:
    - .:/usr/src/app
  
  db:
    image: mariadb:10.3.6
    container_name: "mdb"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_USER = agsuser
      - MYSQL_PASSOWORD = 
    ports:
     - "9906:3306"
    volumes:
    - ./data:/var/lib/mysql
    command: mysqld --innodb-flush-method=O_DSYNC